# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'kaiyan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftIcons'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya'
  # Pods for kaiyan

  target 'kaiyanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kaiyanUITests' do
    # Pods for testing
  end

end
